### ISSUE TITLE
usage of local assets

### ISSUE THREAD

**Issue by yaurora** [netbootxyz/docker-netbootxyz#4]
I have hosted my own copy of netbookxyz via docker, and I downloaded some assets and want to boost network installation from those local resources.
For exmaple I downloaded Proxmox VE and modified proxmox.ipxe to use local resources by setting live_endpoint to my own server ip:

```shell
**set live_endpoint http://192.168.1.100:8080**

:boot
set kernel_url ${live_endpoint}/asset-mirror/releases/download/7.0-1-24e3084c/
imgfree
kernel ${kernel_url}vmlinuz vga=791 video=vesafb:ywrap,mtrr ramdisk_size=16777216 rw quiet ${params} initrd=initrd.magic ${cmdline}
initrd ${kernel_url}initrd
initrd ${kernel_url}proxmox.iso /proxmox.iso
boot
````
However, when i tried to boot the Proxmox installer it still tried to retrive all the resources from github.
So what's the correct approach to use local assets please?

**Comment by antonym** [comment]
Modify boot.cfg and adjust the live_endpoint value:

set live_endpoint http://192.168.1.100:8080

You can drop into your iPXE shell and do a echo ${live_endpoint} to make sure you have the endpoint set. If it's not set, it may have fallen back to the hosted version if the locally version of the menu failed to boot.

**Comment by east4ming** [comment]
> Modify boot.cfg and adjust the live_endpoint value:
> 
> set live_endpoint http://192.168.1.100:8080
> 
> You can drop into your iPXE shell and do a echo ${live_endpoint} to make sure you have the endpoint set. If it's not set, it may have fallen back to the hosted version if the locally version of the menu failed to boot.

I'm having the same problem. What do you mean "it may have fallen back to the hosted version if the locally version of the menu failed to boot."? How should I check my configuration and fix
