### ISSUE TITLE
Add config mount option for TFTP files

### ISSUE THREAD

**Issue by EpicLPer** [netbootxyz/docker-netbootxyz#6]
Heya!

I'm currently trying to set up this Docker Container on my Synology NAS, however I can't bind Port 69 to the Docker container since Synology reserves that port for its own TFTP server functionality.

My suggestion here would be to give a separate mount config option for the TFTP files so I can set a separate location and use the internal Synology TFTP server instead of the Docker integrated one to serve those files. However I'm not sure how easy this would be to do and how easy it'd be to update those files in case the Docker container itself updates.

Thanks already for reading!

**Comment by thelamer** [comment]
https://github.com/linuxserver/docker-netbootxyz/issues/11#issuecomment-968433485
This what you are looking for ?

**Comment by EpicLPer** [comment]
Ah, yes that's exactly what I searched for, thanks!
